sudo: required
language: node_js
services:
  - docker

before_install:
  - docker build -t nilandasd/scrumtracker ./server/

script:
  - docker run -e CI=true nilandasd/scrumtracker npm run test -- --coverage

