sudo: required
language: node_js
services:
  - docker

before_install:
  - docker build -t nilandasd/ScrumTracker .

script:
  - docker run -e CI=true nilandasd/ScrumTracker npm run test -- --coverage

