FROM nginx:1.15.8-alpine

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY ./*.html /usr/share/nginx/html/
COPY ./*.js /usr/share/nginx/html/
COPY ./*.html /usr/share/nginx/html/
COPY ./*.txt /usr/share/nginx/html/
COPY ./*.woff /usr/share/nginx/html/
COPY ./*.woff2 /usr/share/nginx/html/